name: shell command

on: [push]


jobs:
  #name of the job
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a hello
        run: echo "hello Manas"

      - name: multiline script
        run: |
          node -v
          npm -v

  run-windows-command
    runs-on: windows-latest
    steps:
      - name: print current directory in powershell
        run: Get-Location
        
      - name: print current directory in bash
        run: pwd
        shell: bash



      

